# Generated by Django 2.2.4 on 2019-09-09 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0002_auto_20190902_1551'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='movielinks',
            options={'verbose_name': 'Movie Link', 'verbose_name_plural': 'Movie Links'},
        ),
        migrations.AlterField(
            model_name='movie',
            name='category',
            field=models.CharField(choices=[('action', 'ACTION'), ('drama', 'DRAMA'), ('comedy', 'COMEDY'), ('romance', 'ROMANCE')], max_length=10),
        ),
    ]
