# Generated by Django 2.2.4 on 2019-09-15 12:39

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movie', '0006_movie_movie_trailer'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 9, 15, 12, 39, 50, 649441, tzinfo=utc)),
        ),
    ]
